baseURL = 'https://riscv-summit-china.com/'
languageCode = 'zh-CN'
title = 'RISC-V Summit China 2024'
theme = 'ananke'
timeZone = "Asia/Shanghai"
recent_posts_number = 8
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false

[markup.goldmark.renderer]
  unsafe= true

[params]
  custom_css = ["custom.scss"]
  body_classes = "sans-serif"
  site_logo = "/img/riscv-logo.webp"
  date_img = "/img/date.webp"
  title_zh_img = "/img/riscvsummit-title-zh.webp"
  title_en_img = "/img/riscvsummit-title-en.webp"
  subtitle_img = "/img/riscvsummit-subtitle.webp"

[permalinks]
  [permalinks.page]
    posts = '/posts/:slug/'
    posts_redirect = '/posts/:slug/'
  [permalinks.section]
    posts = '/posts/'

[languages]
  [languages.zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '简体中文'
    title = 'RISC-V 中国峰会 2024'
    copyright = 'RISC-V 中国峰会。'
    weight = 1
    hasCJKLanguage = true
    summaryLength = 230
    [languages.zh.params]
      date_format = "2006 年 1 月 2 日"
      [[languages.zh.params.host]]
        name = "浙江大学杭州国际科创中心"
      [[languages.zh.params.co_host]]
        name = "国科大杭州高等研究院"
      [[languages.zh.params.co_host]]
        name = "RISC-V 工作委员会 (RVEI)"
      [[languages.zh.params.organizer]]
        name = "上海苦芽科技有限公司"
      [[languages.zh.params.organizer]]
        name = "广州市智能软件产业研究院"
      [[languages.zh.params.co_organizer]]
        name = "CNRV"
      [[languages.zh.params.co_organizer]]
        name = "CRVA"
      [[languages.zh.params.co_organizer]]
        name = "CRVA 浙江中心"
      [[languages.zh.params.co_organizer]]
        name = "CRVIC"
      [[languages.zh.params.banners]]
        id   = 1
        text = '欢迎参加 RISC-V 中国峰会 2024'
        link = 'https://www.wenjuan.com/t/UZBZJvFH93/'
        link_text = '报名链接'
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        name = "主页"
        url = "#"
        weight = 1
      [[languages.zh.menu.main]]
        name = "新闻"
        url = "#news"
        weight = 5
      [[languages.zh.menu.main]]
        name = "演讲征集"
        url = "#cfp"
        weight = 10
      [[languages.zh.menu.main]]
        name = "赞助商"
        url = "#sponsors"
        weight = 15
      [[languages.zh.menu.main]]
        name = "同期活动"
        url = "#events"
        weight = 20
      [[languages.zh.menu.main]]
        name = "大会议程"
        url = "#agenda"
        weight = 25
      [[languages.zh.menu.main]]
        name = "观众报名"
        url = "#registration"
        weight = 30
      [[languages.zh.menu.main]]
        name = "路线及酒店"
        url = "#venue"
        weight = 35
      [[languages.zh.menu.main]]
        name = "展厅信息"
        url = "#exhibition"
        weight = 40
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'RISC-V Summit China 2024'
    copyright = 'RISC-V Summit China.'
    weight = 2
    [languages.en.params]
      date_format = "January 2, 2006"
      [[languages.en.params.host]]
        name = "ZJU-Hangzhou Global Scientific and Technological Innovation Center"
      [[languages.en.params.co_host]]
        name = "Hangzhou Institute for Advanced Study, UCAS"
      [[languages.en.params.co_host]]
        name = "RVEI"
      [[languages.en.params.organizer]]
        name = "Shanghai Kubuds Technology Co., Ltd."
      [[languages.en.params.organizer]]
        name = "Institute of Intelligent Software, Guangzhou"
      [[languages.en.params.co_organizer]]
        name = "CNRV"
      [[languages.en.params.co_organizer]]
        name = "CRVA"
      [[languages.en.params.co_organizer]]
        name = "CRVA Zhejiang Centre"
      [[languages.en.params.co_organizer]]
        name = "CRVIC"
      [[languages.en.params.banners]]
        id   = 1
        text = 'Welcome to attend RISC-V Summit China 2024'
        link = 'https://www.wenjuan.com/s/bQzaYrS/'
        link_text = 'Registration link'
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "#"
        weight = 1
      [[languages.en.menu.main]]
        name = "News"
        url = "#news"
        weight = 5
      [[languages.en.menu.main]]
        name = "Call for Papers"
        url = "#cfp"
        weight = 10
      [[languages.en.menu.main]]
        name = "Sponsors"
        url = "#sponsors"
        weight = 15
      [[languages.en.menu.main]]
        name = "Co-events"
        url = "#events"
        weight = 20
      [[languages.en.menu.main]]
        name = "Agenda"
        url = "#agenda"
        weight = 25
      [[languages.en.menu.main]]
        name = "Registration"
        url = "#registration"
        weight = 30
      [[languages.en.menu.main]]
        name = "Venue & Accomodation"
        url = "#venue"
        weight = 35
      [[languages.en.menu.main]]
        name = "Exhibition Space"
        url = "#exhibition"
        weight = 40
